<<<<<<< HEAD
exec-once = [workspace 2 silent] firefox
windowrulev2 = workspace 2 silent, class:^(firefox)$
=======
exec-once = zen-browser 
 windowrule = workspace 2 silent, match:title ^(Zen Browser)$
>>>>>>> da27a437 (feat: Update window rules and configuration scripts for improved functionality and consistency)
